/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                luxury: {
                    gold: {
                        50: "#fefce8",
                        100: "#fef9c3",
                        200: "#fef08a",
                        300: "#fde047",
                        400: "#facc15",
                        500: "#eab308",
                        600: "#ca8a04",
                        700: "#a16207",
                        800: "#854d0e",
                        900: "#713f12",
                    },
                    champagne: {
                        50: "#fdf9f0",
                        100: "#fbf1e0",
                        200: "#f6e2c1",
                        300: "#f0d09d",
                        400: "#e8bb75",
                        500: "#d4af37",
                        600: "#c9a96e",
                        700: "#b8860b",
                        800: "#8b6914",
                        900: "#654f0f",
                    },
                    bronze: {
                        50: "#fdf6f0",
                        100: "#faebe0",
                        200: "#f4d5c1",
                        300: "#ecbb9d",
                        400: "#e19b75",
                        500: "#cd7f32",
                        600: "#b8722c",
                        700: "#9d5f22",
                        800: "#824f1c",
                        900: "#6b4118",
                    },
                    pearl: {
                        50: "#fdfdf9",
                        100: "#faf9f2",
                        200: "#f5f4e8",
                        300: "#edebd9",
                        400: "#e0dcc4",
                        500: "#d0c8a8",
                        600: "#b8ad89",
                        700: "#9a8c6b",
                        800: "#7c7055",
                        900: "#645a44",
                    },
                },
                gold: {
                    50: "#fffbeb",
                    100: "#fef3c7",
                    200: "#fde68a",
                    300: "#fcd34d",
                    400: "#fbbf24",
                    500: "#f59e0b",
                    600: "#d97706",
                    700: "#b45309",
                    800: "#92400e",
                    900: "#78350f",
                },
                cream: {
                    50: "#fdfbf7",
                    100: "#faf6ef",
                    200: "#f4ebdb",
                    300: "#ead9c1",
                    400: "#ddc0a0",
                    500: "#c9a876",
                    600: "#b8965f",
                    700: "#9a7c4f",
                    800: "#7d6542",
                    900: "#665337",
                },
            },
            fontFamily: {
                display: ["Playfair Display", "serif"],
                script: ["Cormorant Garamond", "serif"],
                serif: ["Playfair Display", "serif"],
                sans: ["Inter", "sans-serif"],
            },
            fontSize: {
                '8xl': ['6rem', { lineHeight: '1' }],
                '9xl': ['8rem', { lineHeight: '1' }],
            },
            spacing: {
                '18': '4.5rem',
                '88': '22rem',
                '128': '32rem',
            },
            backdropBlur: {
                'xs': '2px',
            },
            animation: {
                "fade-in": "fadeIn 0.5s ease-in-out",
                "slide-up": "slideUp 0.5s ease-out",
                "float": "float 3s ease-in-out infinite",
                "luxury-pulse": "luxuryPulse 2s ease-in-out infinite",
                "gold-shimmer": "goldShimmer 2s infinite",
                "fade-in-up": "fadeInUp 0.8s ease-out forwards",
                "fade-in-down": "fadeInDown 0.8s ease-out forwards",
                "slide-in-left": "slideInLeft 0.8s ease-out forwards",
                "slide-in-right": "slideInRight 0.8s ease-out forwards",
                "scale-in": "scaleIn 0.5s ease-out",
                "bounce-subtle": "bounceSubtle 1s ease-out infinite",
            },
            keyframes: {
                fadeIn: {
                    "0%": { opacity: "0" },
                    "100%": { opacity: "1" },
                },
                slideUp: {
                    "0%": { transform: "translateY(20px)", opacity: "0" },
                    "100%": { transform: "translateY(0)", opacity: "1" },
                },
                float: {
                    "0%, 100%": { transform: "translateY(0px)" },
                    "50%": { transform: "translateY(-10px)" },
                },
                scaleIn: {
                    "0%": { transform: "scale(0.95)", opacity: "0" },
                    "100%": { transform: "scale(1)", opacity: "1" },
                },
                bounceSubtle: {
                    "0%, 20%, 50%, 80%, 100%": { transform: "translateY(0)" },
                    "40%": { transform: "translateY(-5px)" },
                    "60%": { transform: "translateY(-3px)" },
                },
            },
            boxShadow: {
                'luxury': '0 25px 50px -12px rgba(212, 175, 55, 0.25)',
                'luxury-lg': '0 35px 60px -12px rgba(212, 175, 55, 0.35)',
                'inner-luxury': 'inset 0 2px 4px 0 rgba(212, 175, 55, 0.06)',
            },
            backgroundImage: {
                'luxury-gradient': 'linear-gradient(135deg, #d4af37 0%, #c9a96e 50%, #b8860b 100%)',
                'luxury-radial': 'radial-gradient(ellipse at center, #d4af37 0%, #c9a96e 50%, #b8860b 100%)',
                'texture-luxury': "url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGQ9Ik0yMCAwdjQwTTAgMjBoNDBNMjAgMjBMMCA0ME00MCA0MFYwIiBzdHJva2U9InJnYmEoMjEyLDE3NSw1NSwwLjEpIiBzdHJva2Utd2lkdGg9IjEiLz48L2c+PC9zdmc+')",
            },
        },
    },
    plugins: [],
};
